version: '3.8'
services:
  login-ui-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  login-ui-prod:
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: npm run start

  login-ui-local:
    build:
      context: .
      target: local
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=local
    command: npm run dev
